# Generated by Django 4.0.1 on 2022-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported_issue',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
